# template of alembic
"""add-password

Revision ID: 184d9f49d5d4
Revises: 54b8cf706779
Create Date: 2026-05-29 16:04:28.878143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "184d9f49d5d4"
down_revision: Union[str, Sequence[str], None] = "54b8cf706779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )  # setting password can be null

    op.execute(
        "UPDATE employees SET password_hash = 'placeholder' WHERE password_hash IS NULL"
    )  # addding placeholder as value for password where it is null

    op.alter_column(
        "employees", "password_hash", nullable=False
    )  # again making password not to have null values.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "password_hash")
    # ### end Alembic commands ###
