# template of alembic
"""add-role

Revision ID: 40d7b9e29aef
Revises: dbdf8f50d39b
Create Date: 2026-06-01 14:19:24.387185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40d7b9e29aef"
down_revision: Union[str, Sequence[str], None] = "dbdf8f50d39b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('employees', sa.Column('role', sa.Enum('UI', 'UX', 'Developer', 'HR', name='employeerole'), server_default='Developer', nullable=False))

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, nullable=False, server_default="Developer"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
