#template of alembic
"""added status and experience

Revision ID: ce199895d6b3
Revises: 3f206cf9c84e
Create Date: 2026-06-11 08:59:14.730832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce199895d6b3'
down_revision: Union[str, Sequence[str], None] = '3f206cf9c84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_STATUS_ENUM = sa.Enum("Active", "Inactive", "Probation", name="status")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # op.create_unique_constraint(None, 'department', ['name'])
    op.create_index(op.f('ix_employee_department_department_id'), 'employee_department', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_department_employee_id'), 'employee_department', ['employee_id'], unique=False)
    op.drop_constraint(op.f('employee_department_employee_id_fkey'), 'employee_department', type_='foreignkey')
    op.drop_constraint(op.f('employee_department_department_id_fkey'), 'employee_department', type_='foreignkey')
    op.create_foreign_key(None, 'employee_department', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_department', 'department', ['department_id'], ['id'])

    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    
    op.add_column('employees', sa.Column('experience', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE employees SET experience = 1 WHERE experience IS NULL"
    )
    op.alter_column("employees", "experience", nullable=False)

    op.add_column('employees', sa.Column('status', sa.Enum('Active', 'Inactive', 'Probation', name='status'), nullable=True))
    op.execute(
        "UPDATE employees SET status = 'Active' WHERE status IS NULL"
    )
    op.alter_column("employees", "status", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'experience')
    op.drop_column('employees', 'status')
    op.drop_constraint(None, 'employee_department', type_='foreignkey')
    op.drop_constraint(None, 'employee_department', type_='foreignkey')
    op.create_foreign_key(op.f('employee_department_department_id_fkey'), 'employee_department', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('employee_department_employee_id_fkey'), 'employee_department', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_department_employee_id'), table_name='employee_department')
    op.drop_index(op.f('ix_employee_department_department_id'), table_name='employee_department')
    op.drop_constraint(None, 'department', type_='unique')
    op.alter_column('department', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
