# template of alembic
"""add-role

Revision ID: dbdf8f50d39b
Revises: f0b00bcc3063
Create Date: 2026-06-01 14:13:45.760123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbdf8f50d39b"
down_revision: Union[str, Sequence[str], None] = "f0b00bcc3063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_department",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=True),
    )
    op.add_column(
        "employee_department",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "employee_department",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "employee_department",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_employee_department_id"), "employee_department", ["id"], unique=False
    )

    op.add_column(
    "employee_department",
    sa.Column("id", sa.Integer(), nullable=True),
)

    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    op.drop_index(op.f("ix_employee_department_id"), table_name="employee_department")
    op.drop_column("employee_department", "deleted_at")
    op.drop_column("employee_department", "updated_at")
    op.drop_column("employee_department", "created_at")
    op.drop_column("employee_department", "id")
    # ### end Alembic commands ###

